routes:
  - path: /
    file: index.html
  - path: /index.html
    file: index.html
  - path: /app.js
    file: app.js
  - path: /decisions.js
    file: decisions.js
  - path: /style.css
    file: style.css
